### ISSUE TITLE
Enigma : non-euclidian space distortion

### ISSUE THREAD

**Issue by mochiruntime** [Zyfarok/the-euclidian-escape#2]
Prompt the player with something along the lines of "Run against the clock for maintenance" (can also put a clock to confuse the player). When the player performs >360° counter clockwise, the room should changed into a maintenance room much bigger (but there should be a barrier to prevent the player from going to far). The player will need to break something with the bit gun afar in the maintenance room to unlock the enigma (for instance an object blocking giant gears)

**Comment by Zyfarok** [comment]
Not a bad idea. Possible format of the hint :
- "check ... status in the maintenance room 360° behind you"
- or just "behind you", and then 180° "behind", there would be arrows indicating "Cockpit" on the left/right and "Maintenance room" on the right/left (which would be the actual hint)
- or otherwise find a smart way to display a 2D "720° map". ?
